[package]
name = "my_parser_sofia"
version = "0.1.0"
edition = "2021"
description = "my firts rust parser"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8.2"
